object Versions {
    const val gradle = "7.3.1"
    const val kotlin = "1.7.20"
    const val kotlinJvm = "1.7.21"
    const val desugaring = "1.1.5"

    val coreKtx = "1.2.0"
    val appcompat = "1.3.0-alpha01"
    val constraintLayout = "2.0.0-beta8"

    val junit = "4.12"
    val extJunit = "1.1.1"
    val espresso = "3.2.0"

    const val compose_ui_version = "1.3.1"
    const val accompanist_version = "0.28.0"
    const val compose_destinations = "1.7.27-beta"
    const val about_libraries = "10.5.2"
    const val hilt_version = "2.44"
    const val room_version = "2.4.3"
    const val material_dialogs = "1.0.2"

    const val composeMaterialVersion = "1.1.0-alpha06"
    const val androidxCoreVersion = "1.9.0"
    const val lifecycleRuntime = "2.5.1"
    const val activityCompose = "1.6.1"
    const val splashScreen = "1.0.0"
    const val composeUiVersion = "1.3.1"
    const val firebaseBom = "32.1.1"
    const val hiltVersion = "2.44"
    const val roomVersion = "2.4.3"
    const val kotlinSerailization = "1.4.1"
    const val dataStore = "1.0.0"
    const val hiltNavigationComposeVersion = "1.0.0"
    const val composeDestinations = "1.7.27-beta"
    const val cascadeDropdown = "2.0.0-rc02"
    const val composeDialogs = "1.1.1"
    const val composeModalSheet = "0.4.0"
    const val adaptyVersion = "2.4.3"

    const val flurry = "14.2.0"
    const val oneSignal = "[4.0.0, 4.99.99]"
    const val adsIdentifier = "17.1.0"
    const val mpChart = "v3.1.0"
}